export const COURSESDATA = [
    {
      "id": 1,
      "title": "Next.js 14 & React - The Complete Guide",
      "instructor": "Maximilian Schwarzmüller",
      "description": "Learn Next.js 14, React, and all the essential tools to build modern web applications from scratch.",
      "rating": 4.7,
      "numReviews": 19787,
      "lessons": 19,
      "price": 119.99,
      "level": "Intermediate",
      "category": "Web Development",
      "language": "English",
      "releaseDate": "2023-09-01",
      "isFeatured": true,
      'imageUrl': "https://img-c.udemycdn.com/course/240x135/3873464_403c_3.jpg"
    },
    {
      "id": 2,
      "title": "Python for Beginners: Learn Python from Scratch",
      "instructor": "John Doe",
      "description": "An in-depth introduction to Python programming. Perfect for complete beginners looking to start coding.",
      "rating": 4.5,
      "numReviews": 10234,
      "lessons": 25,
      "price": 89.99,
      "level": "Beginner",
      "category": "Programming",
      "language": "English",
      "releaseDate": "2022-06-15",
      "isFeatured": false,
      'imageUrl': "https://img-c.udemycdn.com/course/240x135/3873464_403c_3.jpg"
    },
    {
      "id": 3,
      "title": "Mastering Data Structures & Algorithms in Java",
      "instructor": "Angela Yu",
      "description": "This course takes you from beginner to expert in data structures and algorithms using Java.",
      "rating": 4.9,
      "numReviews": 33456,
      "lessons": 25,
      "price": 129.99,
      "level": "Advanced",
      "category": "Computer Science",
      "language": "English",
      "releaseDate": "2023-01-10",
      "isFeatured": true,
      'imageUrl': "https://img-c.udemycdn.com/course/240x135/3873464_403c_3.jpg"
    },
    {
      "id": 4,
      "title": "Full-Stack Web Development with Django and React",
      "instructor": "Jane Smith",
      "description": "Build real-world web applications using Django for the backend and React for the frontend.",
      "rating": 4.6,
      "numReviews": 5678,
      "lessons": 27,
      "price": 149.99,
      "level": "Intermediate",
      "category": "Web Development",
      "language": "English",
      "releaseDate": "2022-12-20",
      "isFeatured": false
    },
    {
      "id": 5,
      "title": "UI/UX Design Essentials",
      "instructor": "Sarah Lee",
      "description": "A complete guide to creating beautiful and user-friendly designs, covering both UI and UX principles.",
      "rating": 4.8,
      "numReviews": 8479,
      "lessons": 25,
      "price": 99.99,
      "level": "Beginner",
      "category": "Design",
      "language": "English",
      "releaseDate": "2023-03-22",
      "isFeatured": true
    },
    {
      "id": 6,
      "title": "Machine Learning A-Z: Hands-On Python & R In Data Science",
      "instructor": "Kirill Eremenko",
      "description": "Learn machine learning from scratch with practical projects in Python and R.",
      "rating": 4.4,
      "numReviews": 42567,
      "lessons": 28,
      "price": 109.99,
      "level": "Intermediate",
      "category": "Data Science",
      "language": "English",
      "releaseDate": "2021-08-11",
      "isFeatured": false
    },
    {
      "id": 7,
      "title": "iOS Development with Swift: The Complete Guide",
      "instructor": "David Goggins",
      "description": "Master iOS app development using Swift. Build projects and prepare for iOS development jobs.",
      "rating": 4.7,
      "numReviews": 19345,
      "lessons": 29,
      "price": 139.99,
      "level": "Advanced",
      "category": "Mobile Development",
      "language": "English",
      "releaseDate": "2023-05-12",
      "isFeatured": true
    },
    {
      "id": 8,
      "title": "Blockchain Development: From Beginner to Expert",
      "instructor": "Vitalik Buterin",
      "description": "Become a blockchain developer by mastering key concepts and building projects using Ethereum and Solidity.",
      "rating": 4.6,
      "numReviews": 8674,
      "lessons": 21,
      "price": 159.99,
      "level": "Advanced",
      "category": "Blockchain",
      "language": "English",
      "releaseDate": "2023-04-05",
      "isFeatured": true
    },
    {
      "id": 9,
      "title": "Digital Marketing Masterclass: Become a Marketing Expert",
      "instructor": "Gary Vee",
      "description": "Learn digital marketing strategies, including SEO, social media marketing, and email marketing, to grow any business.",
      "rating": 4.3,
      "numReviews": 21234,
      "lessons": 19,
      "price": 79.99,
      "level": "Beginner",
      "category": "Marketing",
      "language": "English",
      "releaseDate": "2021-10-18",
      "isFeatured": false
    },
    {
      "id": 10,
      "title": "Game Development with Unity & C#",
      "instructor": "Brackeys",
      "description": "Learn to develop video games using Unity and C#. Build your first game and level up your skills.",
      "rating": 4.8,
      "numReviews": 17894,
      "lessons": 29,
      "price": 179.99,
      "level": "Intermediate",
      "category": "Game Development",
      "language": "English",
      "releaseDate": "2023-02-28",
      "isFeatured": true
    }
]
  