"""delete username

Revision ID: 931869f11f72
Revises: ed5ab9638364
Create Date: 2024-10-19 03:12:25.857491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '931869f11f72'
down_revision: Union[str, None] = 'ed5ab9638364'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firstname', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'firstname')
    # ### end Alembic commands ###
