"""add-imageurl

Revision ID: a5acd1a8c769
Revises: 476083b47c82
Create Date: 2024-10-19 00:49:07.546451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5acd1a8c769'
down_revision: Union[str, None] = '476083b47c82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('lessons', sa.Column('image_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'image_url')
    op.drop_column('lessons', 'description')
    # ### end Alembic commands ###
