"""index id's

Revision ID: ed5ab9638364
Revises: a5acd1a8c769
Create Date: 2024-10-19 01:43:41.494309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed5ab9638364'
down_revision: Union[str, None] = 'a5acd1a8c769'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_course_enrollments_enrollment_id'), 'course_enrollments', ['enrollment_id'], unique=False)
    op.create_index(op.f('ix_courses_course_id'), 'courses', ['course_id'], unique=False)
    op.create_index(op.f('ix_lessons_lesson_id'), 'lessons', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_modules_module_id'), 'modules', ['module_id'], unique=False)
    op.create_index(op.f('ix_questions_question_id'), 'questions', ['question_id'], unique=False)
    op.create_index(op.f('ix_quizzes_quiz_id'), 'quizzes', ['quiz_id'], unique=False)
    op.create_index(op.f('ix_user_progress_progress_id'), 'user_progress', ['progress_id'], unique=False)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_user_progress_progress_id'), table_name='user_progress')
    op.drop_index(op.f('ix_quizzes_quiz_id'), table_name='quizzes')
    op.drop_index(op.f('ix_questions_question_id'), table_name='questions')
    op.drop_index(op.f('ix_modules_module_id'), table_name='modules')
    op.drop_index(op.f('ix_lessons_lesson_id'), table_name='lessons')
    op.drop_index(op.f('ix_courses_course_id'), table_name='courses')
    op.drop_index(op.f('ix_course_enrollments_enrollment_id'), table_name='course_enrollments')
    # ### end Alembic commands ###
